name: Mirror to GitLab

on:
  push:
    branches:
      - main
permissions:
  contents: read

jobs:
  mirror:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/MintyItanium/Lost-Auction.git
          git push gitlab --force --prune --all
          git push gitlab --force --tags
